var nome = "Fabiano Frange";
var idade = 33;
var idade2 = 10;
var frase = "Japão é o melhor time do mundo!";
//alert(nome + " tem " + idade + " anos!");
//alert(idade+idade2);
console.log(nome);
console.log(idade + idade2);
console.log(frase.replace("Japão", "Brasil"));
//alert(frase.replace("Japão", "Brasil"));
console.log(frase.toUpperCase());